### ISSUE TITLE
Underline control codes not supported

### ISSUE THREAD

**Issue by glennlunder** [demozoo/ansipants#1]
In the new ansi renderer, what I call "Amiga ansi" - escape codes used in Amiga specific text files are not rendered correctly. Even the Windows commandline does a decent job of this, so perhaps it is possible/relatively easy to implement?

Windows 11 command line:

![image](https://user-images.githubusercontent.com/2839057/146648870-b76032a6-1aad-40fd-8cec-afab86bc76f8.png)

Demozoo currently:

![image](https://user-images.githubusercontent.com/2839057/146648897-bdf0c0c5-e92e-40a6-a37f-46168345fc63.png)

Native Amiga:

![image](https://user-images.githubusercontent.com/2839057/146648967-7d2c47f5-87cc-48e3-a552-e83bbbaf3e20.png)

**Comment by gasman** [comment]
Transferred to https://github.com/demozoo/ansipants as this is reproducible outside of Demozoo.

The only thing that's identifiably "weird" about this file (as in, ansipants fails on it when run in 'strict' mode) is the escape sequence right at the start of the file: `\x1b[0m\x1b[0 p\x0c\x1b[0m` - if https://gist.github.com/fnky/458719343aabd01cfb17a3a4f7296797#keyboard-strings is correct, `\x1b[0 p` would be a keyboard reassignment command, but any valid one would have multiple parameters (not just the `0` here). `\x0c` is a form feed character, and I'm not sure how that's meant to be treated - but in any case, removing these sequences still leaves it rendering correctly in Mac iTerm but broken in ansipants and ansilove, so it seems that's just redundant junk.

Looking closer, everything in the ansipants / ansilove rendering is in the correct place except for the horizontal lines, so I suspect it's using 'underline' control codes to achieve those, and neither ansipants nor ansilove is currently implementing them. And indeed, there are a whole load of `\x1b[4m` sequences, which is apparently [the sequence for enabling underline](https://gist.github.com/fnky/458719343aabd01cfb17a3a4f7296797#colors--graphics-mode). So I think that solves the mystery!
